steps:
  # 1. Build the React application
  - name: 'gcr.io/cloudbuild/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/ecommerce-434317/gabogt4-React_E-Commerce'
      - '.'
    # Use a Dockerfile in your repository's root directory
    # This Dockerfile should build your React app and create a production-ready image
    # Example Dockerfile:
    # FROM node:16-alpine
    # WORKDIR /app
    # COPY package*.json ./
    # RUN npm install
    # COPY . .
    # RUN npm run build
    # CMD ["npm", "start"]
    options:
      logging: CLOUD_LOGGING_ONLY

  # 2. Push the built image to Container Registry
  - name: 'gcr.io/cloudbuild/docker'
    args:
      - 'push'
      - 'gcr.io/ecommerce-434317/gabogt4-React_E-Commerce'
    options:
      logging: CLOUD_LOGGING_ONLY

  # 3. Deploy to Cloud Run (optional)
  - name: 'gcr.io/cloudbuild/cloudrun'
    args:
      - 'deploy'
      - 'your-react-app'
      - '--image'
      - 'gcr.io/ecommerce-434317/gabogt4-React_E-Commerce'
      - '--platform'
      - 'managed'
    options:
      logging: CLOUD_LOGGING_ONLY
      # Optional: Set a region for your Cloud Run service
      # --region=us-central1
      # Optional: Set a custom domain for your Cloud Run service
      # --domain=your-custom-domain.com
      # Optional: Set a custom URL path for your Cloud Run service
      # --path=your-custom-path
